Basic Variable Types

In [2]:
a = 1 + 1
typeof(a)   # Int64

a = "Hello"
typeof(a)   # String

String

Numerical Types in Julia - https://www.matecdev.com/posts/julia-types-numerical.html

In [3]:
Float64(2)  # 2.0 (double-precision)
Float32(2)  # 2.0f0 (single-precision)
Float16(2)  # Float16(2.0) (half-precision)

Float16(2.0)

To convert integers to float they have to coincide with an integer exactly

In [ ]:
Int64(2.0)          # 2
Int(2.4)            # Error!
floor(Int64, 2.4)   # 2
ceil(Int64, 2.4)    # 3
round(Int64, 2.4)   # 2 

Integer Division

In [6]:
a = 1/2         # 0.5 (Float64)

div(10, 3)      # 3
÷(10, 3)        # 3
a = 10 ÷ 3      # 3

rem(10, 3)      # 1
10 % 3          # 1

1

In [7]:
a = 2       # Int64 by default
a = 1/2^64  # Infinity - 2^64 overflows to 0. 1/0 gives infinity

Inf

In [8]:
2^64        # returns 0 - default overflow value

1/2.0^64    # 5.421010862427522e-20
(1/2)^64    # 5.421010862427522e-20
1.0/2^64    # Inf

Inf

In [10]:
x = false
!x          # returns the opposite of x

if x
    # do something
end

if @isdefined(ge) # checks if a variable is defined
    print("ge is defined")
end


In [ ]:
boolToInt = true + true     # Boolean is a subtype of int - will return 2


In [11]:
"Hello"     # string
'H'         # char
'Hello'     # error - char cannot contain multiple characters

ErrorException: cannot document the following expression:

H


In [12]:
"Hello " * "wor" * "ld"         # String concatenate
string("Hello", " ", "world")

"Hello world"

Converting numbers to strings

In [23]:
string(1/7)                 # returns "0.14285714285714285"
"$(1/7)"                    # returns "0.14285714285714285"
`@sprintf("%6.4f", 1/7)`    # returns `"0.1429"`

ErrorException: cannot document the following expression:

(Printf).format(Printf.Format{Base.CodeUnits{UInt8, String}, Tuple{Printf.Spec{Val{'f'}}}}(UInt8[0x25, 0x2e, 0x34, 0x66], UnitRange{Int64}[1:0, 5:4], (%.4f,)), 1 / 7)


Concatenate numbers to a string

In [14]:
string("In ancient Babylon they approximated pi to 25/8, which is ", 25/8)

"In ancient Babylon they approximated pi to 25/8, which is 3.125"

String interpolation

In [15]:
"In ancient Babylon they approximated pi to 25/8, which is $(25/8)"


"In ancient Babylon they approximated pi to 25/8, which is 3.125"

In [16]:
rmse = 1.5; mse = 1.1; R2 = 0.94
"Our model has a R^2 of $(R2), rmse of $(rmse), and mse of $(mse)"

"Our model has a R^2 of 0.94, rmse of 1.5, and mse of 1.1"

We can use c-style printf to limit the number of decimal point or to use a specific scientific notation

%.4f - 4 decimal digits - 100.1429
%.4e - Scientific notation with 4 digits - 1.4286e-05

In [21]:
using Printf
str = @sprintf("Archimedes approximated pi to 22/7, which is %.4f...", 22/7)

"0.1429"

For loops - 

In [5]:
x = 0
for k in 1:100000       # note includes the left hand and the right hand of the range
    x = x + (1/k)^2
end
x

1.6449240668982423

In [7]:
for i in 1:3
    for j in 1:3
        print("i=", i, " j=", j, "\n")
    end
end

i=1 j=1
i=1 j=2
i=1 j=3
i=2 j=1
i=2 j=2
i=2 j=3
i=3 j=1
i=3 j=2
i=3 j=3


Julia style nested loop

In [9]:
for i in 1:3, j in 1:3
    print("i=", i, " j=", j, "\n")
end

i=1 j=1
i=1 j=2
i=1 j=3
i=2 j=1
i=2 j=2
i=2 j=3
i=3 j=1
i=3 j=2
i=3 j=3


Julia even nicer loops

In [11]:
for i ∈ 1:3, j ∈ 1:3
    print("i=", i, " j=", j, "\n")
end

i=1 j=1
i=1 j=2
i=1 j=3
i=2 j=1
i=2 j=2
i=2 j=3
i=3 j=1
i=3 j=2
i=3 j=3


Break and Continue

Note: they are bad practice, use only as placeholders for unclompleted code

In [12]:
x = 0
for k ∈ 1:100000
    term = (1/k)^2
    x = x + term
    if (abs(term) < 1e-10) break end 
end

In [14]:
numbers = randn(100)
sum = 0
for k in numbers
    if (k==0) continue end
    sum = sum 

UndefVarError: UndefVarError: term not defined

Functions

In [17]:
function sum_zeta(s, nterms)
    x = 0
    for n in 1:nterms
        x = x + (1/n)^s
    end
    return x
end


sum_zeta (generic function with 1 method)

In [18]:
sum_zeta(2, 100000)

1.6449240668982423

One-line function

In [19]:
sum_zeta(s, nterms) = sum(1/n^s for n=1:nterms)

sum_zeta (generic function with 1 method)

In [20]:
sum_zeta(2, 100000)

1.6449240668982423

Optional arguments

In [24]:
sum_zeta(s, nterms=10000) = sum(1/n^s for n=1:nterms)

sum_zeta(2)

1.6448340718480652

To make a keword argument place  semicolon before that argument

In [25]:
sum_zeta(s; nterms=10000) = sum(1/n^s for n=1:nterms)

sum_zeta(2)
sum_zeta(2, nterms = 1e6)

1.64493306684877

Multiple outputs are returned as a tuple

In [27]:
function circle(r)
    area = π * r^2
    circumference = 2π * r
    return area, circumference
    
end

a, c = circle(1.5)

(7.0685834705770345, 9.42477796076938)

In [28]:
shape = circle(1.5)
shape[1]
shape[2]
a, c = shape

(7.0685834705770345, 9.42477796076938)

Functions usually modify their inputs. The convention is to append a ! in the end of the function name that changes the inputs

In [29]:
function add_one!(x)
    x .= x .+ 1
end

x = [1,2,3]
add_one!(x)

3-element Vector{Int64}:
 2
 3
 4

Anonymous functions

In [31]:
function secant(f, a, b, rtol, maxIters)
    iter = 0
    while abs(b-a) > rtol*abs(b) && iter < maxIters
        c,a = a,b
        b = b + (b-a) / (f(c)/f(b)-1)
        iter = iter + 1
    end
    return b
end 

secant (generic function with 1 method)

In [32]:
ϕ = secant(X -> X^2 - X - 1, 1, 2, 1e-15, 10)

2.0

Calling functions in a separate file -
Use the include function with the path to the file

In [ ]:
include("path/to/file.jl")

Arrays, vectors, and matrices

In [33]:
A = [1 2 3; 1 2 4; 2 2 2]       # 3x3 Matrix(Float64)
A = [1 2 3;
     1 2 4;
     2 2 2]

3×3 Matrix{Int64}:
 1  2  3
 1  2  4
 2  2  2

In [34]:
b1 = [4.0, 5, 6]        # 3 element Vector(Float64)
b2 = [4.0; 5; 6]        # 3 element Vector(Float64)
m1 = [4.0 5 6]          # 1x3 Matrix(Float64)

1×3 Matrix{Float64}:
 4.0  5.0  6.0

In [35]:
A = ["hello", 1, 2, 3]


4-element Vector{Any}:
  "hello"
 1
 2
 3

In [36]:
v = [1/n^2 for n = 1:100000]
x = sum(v)

1.644924066898228

When using parenthesis instead of the square backets, Julia will produce a slightly different object: a generator.

This will only producce the required values when needed.

In [ ]:
gen = (1/n^2 for n=1:100000)
x = sum(gen)

Undefined arrays - better we are only allocating the memory without initilizing it with zeroes even

In [39]:
n = 5
A1 = Array{Float64}(undef, n, n)
A2 = Matrix{Float64}(undef, n, n)

V1 = Array{Float64}(undef, n)
V2 = Vector{Float64}(undef, n)


5-element Vector{Float64}:
 6.3659873744e-314
 1.0609978957e-313
 1.27319747483e-313
 2.1219957944e-314
 8.4019894917e-312

In [40]:
A = Array{String}(undef, n)
A = Array{Any}(undef, n)

5-element Vector{Any}:
 #undef
 #undef
 #undef
 #undef
 #undef

In [41]:
v = Array{Float64}(undef, 0)

Float64[]

In [42]:
v = Float64[]

Float64[]

In [43]:
v = []

Any[]

In [45]:
A = zeros(8,9)
B = ones(8, 9)

8×9 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [46]:
C = rand(6,6)

6×6 Matrix{Float64}:
 0.191493  0.287348  0.66946   0.924031  0.0798707  0.797868
 0.480044  0.140499  0.34773   0.758746  0.0176689  0.907817
 0.136655  0.766464  0.547338  0.985306  0.873089   0.804034
 0.232617  0.965649  0.432608  0.919206  0.732624   0.715152
 0.410513  0.377136  0.5951    0.10094   0.0570057  0.59912
 0.46776   0.636297  0.500331  0.543724  0.710328   0.155327

In [47]:
using LinearAlgebra

M = 5I + rand(2,2)


2×2 Matrix{Float64}:
 5.98081   0.889244
 0.927222  5.6827

In [49]:
f(x) = 3x^3/(1+x^2)
x = [2π/n for n=1:30]
y = f.(x)

30-element Vector{Float64}:
 18.383886633134814
  8.55770151410267
  5.11671431742654
  3.353333929033819
  2.3082162000107957
  1.6431863658206738
  1.2015046969739323
  0.8989201052199165
  0.6862922515493683
  0.5335238620487099
  ⋮
  0.0646159000414539
  0.056913991216668146
  0.05037752063018935
  0.0447960758761785
  0.04000285371284216
  0.035864552856086473
  0.03227383743757451
  0.029143663711431032
  0.026402970924539096

In [50]:
y = sin.(x)

30-element Vector{Float64}:
 -2.4492935982947064e-16
  1.2246467991473532e-16
  0.8660254037844387
  1.0
  0.9510565162951535
  0.8660254037844386
  0.7818314824680298
  0.7071067811865475
  0.6427876096865393
  0.5877852522924731
  ⋮
  0.28173255684142967
  0.2697967711570243
  0.25881904510252074
  0.2486898871648548
  0.23931566428755774
  0.23061587074244017
  0.2225209339563144
  0.21497044021102407
  0.20791169081775931

In [52]:
y = 2x.^2 + 3x.^5 - 2x.^8

30-element Vector{Float64}:
     -4.828671033653536e6
 -18039.263768983117
   -610.7857528421777
    -40.50500091388652
      0.12239075156841928
      3.0788623155395416
      2.5165970179806223
      1.8406756088311296
      1.3594357907060943
      1.0347659706787375
      ⋮
      0.16874585207464307
      0.15375911701431397
      0.14072317776024484
      0.12930739401638117
      0.1192493881563927
      0.11033861036842828
      0.10240437795375669
      0.09530704253783058
      0.08893137900051265

In [54]:
y = @__dot__ 2x^2 + 3x^5 - 2x^8

30-element Vector{Float64}:
     -4.828671033653536e6
 -18039.263768983117
   -610.7857528421777
    -40.50500091388652
      0.12239075156841928
      3.0788623155395416
      2.5165970179806223
      1.8406756088311296
      1.3594357907060943
      1.0347659706787375
      ⋮
      0.16874585207464307
      0.15375911701431397
      0.14072317776024484
      0.12930739401638117
      0.1192493881563927
      0.11033861036842828
      0.10240437795375669
      0.09530704253783058
      0.08893137900051265

In [1]:
A = rand(6)
A[begin]
A[end]

0.4182903702084776

In [3]:
A = rand(6,6)
B = A[begin:2:end,begin:2:end]
C = A[1:2:3, 1:2:5]

2×3 Matrix{Float64}:
 0.490065  0.650766  0.555054
 0.789947  0.135769  0.922114

Logical Indexing

In [9]:
A = rand(6,6)
A[A .< 0.5] .= 0 # conditional indexing
# A .< 0.5 creates an array of booleans

20-element view(::Vector{Float64}, [3, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 24, 26, 27, 28, 30, 32, 33, 35, 36]) with eltype Float64:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

Iterating over an Array

In [11]:
A = rand(6)

for i ∈ eachindex(A)
    println(string("i=$(i) A[i]=$(A[i])"))
end

i=1 A[i]=0.48280924260278446
i=2 A[i]=0.5805539733179411
i=3 A[i]=0.07139432641042165
i=4 A[i]=0.5650204894081494
i=5 A[i]=0.4457510481116064
i=6 A[i]=0.6553933507552993


In [13]:
A = rand(6,6)

for i ∈ 1:size(A,1), j ∈ 1:size(A,2)
    println(string("i=$(i) j=$(j) A[i,j]=$(A[i,j])"))
end

i=1 j=1 A[i,j]=0.37541815701664905
i=1 j=2 A[i,j]=0.49272578856722204
i=1 j=3 A[i,j]=0.9739186189475326
i=1 j=4 A[i,j]=0.47147024759458755
i=1 j=5 A[i,j]=0.27862860963662517
i=1 j=6 A[i,j]=0.1796450331935483
i=2 j=1 A[i,j]=0.9012555555431941
i=2 j=2 A[i,j]=0.6604987970963634
i=2 j=3 A[i,j]=0.31597332541685585
i=2 j=4 A[i,j]=0.30518821955650555
i=2 j=5 A[i,j]=0.1573994770051622
i=2 j=6 A[i,j]=0.8965264570881125
i=3 j=1 A[i,j]=0.1677893932885277
i=3 j=2 A[i,j]=0.9945144671936252
i=3 j=3 A[i,j]=0.6816726560619255
i=3 j=4 A[i,j]=0.38944990849923167
i=3 j=5 A[i,j]=0.42873933618839255
i=3 j=6 A[i,j]=0.2789235926566792
i=4 j=1 A[i,j]=0.5527930376050862
i=4 j=2 A[i,j]=0.8480765683418183
i=4 j=3 A[i,j]=0.5098478216542336
i=4 j=4 A[i,j]=0.4270037493880544
i=4 j=5 A[i,j]=0.004978748141870715
i=4 j=6 A[i,j]=0.8476642086629517
i=5 j=1 A[i,j]=0.13400291087519356
i=5 j=2 A[i,j]=0.9510039647966851
i=5 j=3 A[i,j]=0.06955082345940744
i=5 j=4 A[i,j]=0.13965278077264298
i=5 j=5 A[i,j]=0.9737806780538915
i

axes() returns the indices of each dimension of an array
firstindex(A, dim)
lastindex(A, dim)
similar(Array{Float64}, axes(A)) - allocates an array with the same indices as A

In [14]:
A = rand(6,6)
for i ∈ axes(A,1), j ∈ axes(A,2)
    println(string("i=$(i) j=$(j) A[i,j]=$(A[i,j])"))
end

i=1 j=1 A[i,j]=0.36473639754557285
i=1 j=2 A[i,j]=0.8418614209906288
i=1 j=3 A[i,j]=0.17598202402883545
i=1 j=4 A[i,j]=0.7774080296598209
i=1 j=5 A[i,j]=0.8722500579533251
i=1 j=6 A[i,j]=0.3257782293635014
i=2 j=1 A[i,j]=0.9269848276041295
i=2 j=2 A[i,j]=0.5184378154800565
i=2 j=3 A[i,j]=0.578373808581286
i=2 j=4 A[i,j]=0.5725666478764179
i=2 j=5 A[i,j]=0.530733707053744
i=2 j=6 A[i,j]=0.6901087049634445
i=3 j=1 A[i,j]=0.6190327353874071
i=3 j=2 A[i,j]=0.20287347725835625
i=3 j=3 A[i,j]=0.40123118720154094
i=3 j=4 A[i,j]=0.21950468393359335
i=3 j=5 A[i,j]=0.4476692182551175
i=3 j=6 A[i,j]=0.34530339800008514
i=4 j=1 A[i,j]=0.6994114420874331
i=4 j=2 A[i,j]=0.3031063860174521


i=4 j=3 A[i,j]=0.07024476781883782
i=4 j=4 A[i,j]=0.11964053927489038
i=4 j=5 A[i,j]=0.06551117346692614
i=4 j=6 A[i,j]=0.6553158029990159
i=5 j=1 A[i,j]=0.6127927093119934
i=5 j=2 A[i,j]=0.8000155021121635
i=5 j=3 A[i,j]=0.8324183932461379
i=5 j=4 A[i,j]=0.2840201983490295
i=5 j=5 A[i,j]=0.02407615872714064
i=5 j=6 A[i,j]=0.1710468013512797
i=6 j=1 A[i,j]=0.6435623743409993
i=6 j=2 A[i,j]=0.9473783366072495
i=6 j=3 A[i,j]=0.5671505735250615
i=6 j=4 A[i,j]=0.9540770957019011
i=6 j=5 A[i,j]=0.03518544098998544
i=6 j=6 A[i,j]=0.1779608012652747


Matrix multiplcation

A * B - will result in a normal matrix multiplication
A * v - will multiply the matrix with the vector
A .* B - element-wise multiplication

In [16]:
v = rand(1000)
w = rand(1000)
z = v'w      # dot product

255.410485473247

Backslash operator -
For square matrices, Julia will try to solve the linear system, while for rectangle matrices, it will seek for the least squares solution

In [20]:
b1 = [4.0, 5, 6]        # 3-element Vector{Float64}
b2 = [4.0; 5; 6]        # 3-element Vector{Float64}
m1 = [4.0 5 6]          # 1x3 Matrix{Float64}

X = A\b1                # solves A*x = b
X = A\b1                # solves A*x = b
X = A\m1                # Error!

DimensionMismatch: DimensionMismatch: arguments must have the same number of rows

pushfirst!
popfirst!
splice!(A,i)
deleteat!(A,i)

In [21]:
A = Float64[]       # Equivalent to A=Array{Float64}(undef, 0)
push!(A, 4)         # Adds the number 4 at the ne dof the Array
push!(A, 3)         # Addes the number 3 at the end of the Array
v = pop!(A)

3.0